### ISSUE TITLE
[FEATURE] Charting Improvements

### ISSUE THREAD

**Issue by NicoSjokk** [IT2901Nordic2024/frontend#100]
**What user story is this feature related to?**
User Story: 7
User Story Title: As a user i want to be able to see a timeline of my tracked habits 

**What does this feature entail?**
Charting functionality for handling bigger datasets. Managable chart size with navigation between weeks 

**Describe a suggested implentation**
Changes to how Apexcharts are implemented, new Shadcn buttons for navigation

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Implementing week handling logic to charts
- [ ] Navigation between weeks

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] Code is commented
- [ ] Handling big datasets is managable 
- [ ] no new errors arise from the new logic
