### ISSUE TITLE
[FEATURE] Clickeable cards in footer

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#50]
**What does this feature entail?**
As of earlier you could only click on each icon for routing, as well as that each icon was slightly to the left. This issue involve cleaning up the existing code, as well as making every part of the footer clickable.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Make each part of the footer clickable instead of the icons
- [x] Remove positioning for icons
- [x] Clean up in code

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Every part of the footer should be centered in the respective cards
- [x] Everything that ends up under the footer should be pushed up
