### ISSUE TITLE
[FEATURE] Create analytics page

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#53]
**What user story is this feature related to?**
User Story 7
User Story Title: As a user i want to be able to see a timeline of my tracked habits

**What does this feature entail?**
Create an analytics page with overview of the tracked habit you choose to click into. The overview should include history of the habit in a chart, but may also include a calender, goals and other useful information.

**Task list**
- [x] Create a basic page that shows possible analytics
- [x] Connect the chart to this page
- [x] Connect the analytics page to the relevant habit

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Analytics pages are shown
- [x] Correct habit's analytics are shown
- [x] Code is commented

**Additional context**
This is needed to gather different types of information about a habit to one page.
