### ISSUE TITLE
[FEATURE] Habit Goals

### ISSUE THREAD

**Issue by NicoSjokk** [IT2901Nordic2024/frontend#57]
**What user story is this feature related to?**
User Story 13
User Story Title: As a user I want to be able to set myself goals connected to my habit tracking 

**What does this feature entail?**
Implement setting and tracking goals for a specific habit, and view progress

**Describe a suggested implentation**
Implement a configurable goal setting page in the ui, and set an "Expected" variable in the habit chart (marker).

**Task list**
- [x] Set up a option to add goal in the analytics page
- [x] Create a pop up for adding a goal
- [x] Connect the goal chart to the analytics page when a goal is added

**Acceptance criteria**
- [x] Functional goal pop up
- [x] Commented code
