### ISSUE TITLE
[FEATURE] Update chart to new json data format

### ISSUE THREAD

**Issue by NicoSjokk** [IT2901Nordic2024/frontend#59]
**What user story is this feature related to?**
User Story 10
User Story Title: As a user i want to be able to see a timeline of my tracked habits

**What does this feature entail?**
Update to the charting of user data

**Describe a suggested implentation**
Changing data handling in the chart

**Task list**
- [x] Change how chart component handle incoming data
- [x] Add a timestamp converter (from timestamp format to datetime)

**Acceptance criteria**
- [x] Charting functionality is working
