### ISSUE TITLE
[FEATURE] Create goal chart

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#63]
**What user story is this feature related to?**
User Story: 14
User Story Title: As a user I want to be able to view how my progress towards my goal

**What does this feature entail?**
Create the goal chart for viewing progress for a goal connected to a habit.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create a goal chart with expected and actual data
- [ ] Connect to backend, this means sending configuration details using an API

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Code is commented
- [x] Goals showing in the goal chart
