### ISSUE TITLE
[FEATURE] Edit Habit API connection

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#69]
**What user story is this feature related to?**
User Story: 9
User Story Title: As a user i want to be able to change / delete tracked data

**What does this feature entail?**
Connect "EditHabitPage" to the backend API.

**Task list**
- [x] Connect to API in the api folder
- [x] Use the API in EditHabitPage

**Acceptance criteria**
- [x] Code is commented
- [x] Using API
- [x] The user can edit a habit
