### ISSUE TITLE
[FEATURE] Fix device side shown when editing habits

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#73]
**What user story is this feature related to?**
User Story: 9
User Story Title: As a user i want to be able to change / delete tracked data

**What does this feature entail?**
Fix so that "None" is shown when editing a habit if the habit is connected to none of the device sides.

**Task list**
- [x] Check if the habit has a side connected to it
- [x] Show "None" if no side is connected

**Acceptance criteria**
- [x] Code is commented
- [x] "None" shows if no side is connected
