### ISSUE TITLE
[FEATURE] Create profile page

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#76]
**What user story is this feature related to?**
User Story: 8
User Story Title: As a user I wish to change my user information (name, email, password, profile picture) 

**What does this feature entail?**
Users should be able to edit their user information, which means username, email and password. This should be done through a profile page accessable from the navbar / footer.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create a basic design for the profile page
- [x] Create a field for email
- [x] Create a field for name
- [x] Create fields for changing password
- [x] Connect this page to the navbar / footer

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Code is commented
- [ ] Tests are updated
- [x] The page should be accessible and each field changeable
