### ISSUE TITLE
[FEATURE] User confirmation when editing / adding habits

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#78]
**What user story is this feature related to?**
User Story: 6 & 9
User Story Titles: 
- As a user i want to be able to add and remove tracked habits on each side of the device
- As a user i want to be able to change/ delete tracked data

**What does this feature entail?**
This feature should make it clear to the user if editing / adding a habit is successfull.

**Describe a suggested implentation**
- The user should get a confirmation pop-up if a habit is successfully edited / added.
- There should be a loading indication after clicking the button for adding / saving edits, so that the user know the click was done.

**Task list**
- [x] Create confirmation pop-up when successfully adding a habit
- [x] Create confirmation pop-up when successfully editing a habit
- [x] Add a loading indicator after clicking the button for adding a new habit
- [x] Add a loading indicator after clicking the button for saving changes done to a habit

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Code is commented
- [x] There is confirmation when both adding and editing a habit successfully
- [x] There is a loading indication when clicking the button for adding / editing a habit
