### ISSUE TITLE
[FEATURE] Delete habit API connection

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#82]
**What user story is this feature related to?**
User Story: 9
User Story Title: As a user i want to be able to change/ delete tracked data

**What does this feature entail?**
Connect the api for deleting a habit. Connect the button for deleting a habit to this api call.

**Task list**
- [x] Set up the API call function
- [x] Connect the function to the delete button and send the user back to the habit page when done
- [x] Add confirmation message before deleting

**Acceptance criteria**
- [x] Code is commented
- [x] The habit is deleted from the backend when clicking delete
