### ISSUE TITLE
[FEATURE] Create device page

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#84]
**What user story is this feature related to?**
User Story: 3
User Story Title: As a user I want to be able to connect to my device through a website

**What does this feature entail?**
Create a device page where the user is able to see which habit is connected to each side. If no device is connected the user should see a page for connecting to a device. From this page the user should be able to disconnect from device. Connect the new page to the footer. Update the icons accordingly.

**Task list**
- [x] Create basic device page
- [x] Button for disconnecting / connecting to device
- [x] Create device icon
- [x] Update icons in footer
- [x] Set up paths
- [x] Create a model of the device
- [x] Connect to API to fetch device-side information

**Acceptance criteria**
- [x] Code is commented
- [x] Device page is made
- [x] Possible to disconnect / connect to device
- [x] The model works
