### ISSUE TITLE
[FEATURE] Functional navbar

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#86]
**What does this feature entail?**
Update the code so that the navbar is functional while in desktop view, and hidden while in mobile view.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Edit Layout inside App to hide / show footer and navbar based on window size
- [x] Update the navbar to have clickable fields such as in the footer

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Code is commented
- [x] Navbar is functional
- [x] Navbar shows while in desktop view and footer shows while in mobile view
