### ISSUE TITLE
[ENHANCEMENT] Update unused functionality to be presentable

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#89]
**What does this feature entail?**
Update unused functionality and minor styling changes so that the project is presentable

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Remove routing for Connect Device page
- [ ] Add deviceID for user sign up

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] Code is commented
