### ISSUE TITLE
[FEATURE] Calender functionality

### ISSUE THREAD

**Issue by NicoSjokk** [IT2901Nordic2024/frontend#90]
**What user story is this feature related to?**
User Story: 7
User Story Title: AAs a user i want to be able to see a timeline of my tracked habits

**What does this feature entail?**
Calender functionality that shows the dates where entries (habit events) have been registered.

**Describe a suggested implentation**
Shadcn provides a good looking calender. creating functionality for selecting between and parsing json data for both counter habits and timer habits to communicate with this calender will be the main task behind this issue. The logic should also be encapsulated within its own component for maintainability/ modifyability

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create the calender using shadcn
- [x] parse json data for both counter and timer habits
- [x] pass data to component and have it display on the analytics page clearly 

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Code is commented
- [ ] Code is tested and no new errors are created

**Additional context**
No additional context
