### ISSUE TITLE
[FEATURE] Connect user functionality from backend

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#92]
**What user story is this feature related to?**
User Story: 2
User Story Title: As a user i want to be able to create a user and log in

**What does this feature entail?**
Connecting the design up with functionality from the backend, so that a user is able to sign up and log in.

**Task list**
- [ ] Connect to API for retrieving and creating user information

**Acceptance criteria**
- [ ] Code is commented
- [ ] User is able to sign up, log in and out, as well as seeing their data accordingly.
