### ISSUE TITLE
[FEATURE] Connect to backend API for goals

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#94]
**What user story is this feature related to?**
User Story: 13 and 14
User Story Titles:
- As a user I want to be able to set myself goals connected to my habit tracking
- As a user I want to be able to view how my progress towards my goal

**What does this feature entail?**
Set up connection to the goal APIs. Only show goal if there is a goal connected to that habit.

**Task list**
- [x] Connect to setHabitGoal API
- [x] Connect to getHabitGoal API
- [x] Update the analytics page to be working with the API logic

**Acceptance criteria**
- [x] Code is commented
- [x] Both APIs work
