### ISSUE TITLE
[DOC] Code clean up and documentation

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#97]
**What does this issue entail?**
The code needs a clean up, better organising and comments.

**Task list**
- [ ] Make sure everything is thoroughly documented
- [ ] Clean up in code to make it more readable

**Acceptance criteria**
- [ ] Code is commented
- [ ] Code is easily readable
