### ISSUE TITLE
[TESTING] Update tests

### ISSUE THREAD

**Issue by Runarannem** [IT2901Nordic2024/frontend#99]
**What does this feature entail?**
Write and update thorough tests, both unit tests and E2E tests.

**Task list**
- [x] Test *calender* component
- [ ] Test *chart* components
- [x] Test *deviceSVG* component
- [x] Test *footer* component
- [x] Test *habitCard* component
- [x] Test *LoadingSpinner* component
- [x] Test *navBar* component
- [x] Test *summary* component
- [ ] Test *button* shadcn component
- [ ] Test *button2* shadcn component
- [x] Test *calendar* shadcn component
- [ ] Test *card* shadcn component
- [ ] Test *coolCard* shadcn component
- [ ] Test *form* shadcn component
- [ ] Test *input* shadcn component
- [ ] Test *label* shadcn component
- [ ] Test *select* shadcn component
- [ ] Test *tabs* shadcn component
- [ ] Test *toast* shadcn components
- [x] Test *AddGoal* page
- [x] Test *AddHabit* page
- [x] Test *Analytics* page
- [x] Test *Device* page
- [x] Test *EditGoal* page
- [x] Test *EditHabit* page
- [x] Test *Login* page
- [x] Test *MyHabits* page
- [x] Test *UserSignup* page
- [ ] Test *Verification* page

**Acceptance criteria**
- [x] Code is commented
- [x] All tests run
- [ ] Prettier is run
